runtime: python39
entrypoint: gunicorn -b :$PORT app:app

env_variables:
  FLASK_ENV: production
  SECRET_KEY: 81e58d1e71693f45a7cebb8a448ec05a
  DATABASE_URL: sqlite:///instance/app.db
  GOOGLE_CLIENT_ID: tu_google_client_id
  GOOGLE_CLIENT_SECRET: tu_google_client_secret

instance_class: F2
service: default

automatic_scaling:
  target_cpu_utilization: 0.65
  max_instances: 2
